package com.nimbleflow.api.domain.purchase;

import java.time.ZonedDateTime;
import java.util.UUID;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;
import com.nimbleflow.api.config.DynamoDBConfig.ZonedDateTimeConverter;
import com.nimbleflow.api.domain.purchase.enums.PaymentMethod;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Data
@Builder
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "purchase")
public class Purchase {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private UUID id;

    @DynamoDBAttribute
    private UUID orderId;

    @DynamoDBAttribute
    private UUID tableId;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = ZonedDateTimeConverter.class)
    private ZonedDateTime purchaseDate;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    private PaymentMethod paymentMethod;

    @DynamoDBAttribute
    private boolean active;

}