version: '3.9'

services:
  nimbleflow.aspnetcore.hub:
    container_name: nimbleflow.aspnetcore.hub
    image: ${CONTAINER_REGISTRY}/nimbleflow.aspnetcore.hub:${TAG:-latest}
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    ports:
      - "10504:10504"
      - "10505:10505"

  nimbleflow.aspnetcore:
    container_name: nimbleflow.aspnetcore
    image: ${CONTAINER_REGISTRY}/nimbleflow.aspnetcore:${TAG:-latest}
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - SQL_CONNECTION_STRING=${SQL_CONNECTION_STRING}
      - HUB_SERVER_URL=${HUB_SERVER_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_SERVICE_URL=${AWS_S3_SERVICE_URL}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
    ports:
      - "10506:80"

  nimbleflow.java:
    container_name: nimbleflow.java
    image: ${CONTAINER_REGISTRY}/nimbleflow.java:${TAG:-latest}
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - NO_SQL_DATABASE_PATH=${NO_SQL_DATABASE_PATH}
      - NIMBLEFLOW_JAVA_API_USERNAME=${NIMBLEFLOW_JAVA_API_USERNAME}
      - NIMBLEFLOW_JAVA_API_PASSWORD=${NIMBLEFLOW_JAVA_API_PASSWORD}
      - NIMBLEFLOW_JAVA_API_INTEGRATION_TOKEN=${NIMBLEFLOW_JAVA_API_INTEGRATION_TOKEN}
      - NIMBLEFLOW_JAVA_API_JWT_SIGNING_KEY=${NIMBLEFLOW_JAVA_API_JWT_SIGNING_KEY}
    ports:
      - "10507:8080"