version: '3.9'

services:
  nimbleflow.aspnetcore:
    container_name: nimbleflow.aspnetcore
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - SQL_DATABASE_SERVER=${SQL_DATABASE_SERVER}
      - SQL_DATABASE_PORT=${SQL_DATABASE_PORT}
      - SQL_DATABASE_DATABASE=${SQL_DATABASE_DATABASE}
      - SQL_DATABASE_USER=${SQL_DATABASE_USER}
      - SQL_DATABASE_PASSWORD=${SQL_DATABASE_PASSWORD}
    ports:
      - "10502:80"
      - "10503:443"

  nimbleflow.java:
    container_name: nimbleflow.java
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - NO_SQL_DATABASE_PATH=${NO_SQL_DATABASE_PATH}
      - NIMBLEFLOW_JAVA_API_USERNAME=${NIMBLEFLOW_JAVA_API_USERNAME}
      - NIMBLEFLOW_JAVA_API_PASSWORD=${NIMBLEFLOW_JAVA_API_PASSWORD}
      - NIMBLEFLOW_JAVA_API_INTEGRATION_TOKEN=${NIMBLEFLOW_JAVA_API_INTEGRATION_TOKEN}
      - NIMBLEFLOW_JAVA_API_JWT_SIGNING_KEY=${NIMBLEFLOW_JAVA_API_JWT_SIGNING_KEY}
    ports:
      - "10504:8080"