version: '3.9'

services:
  nimbleflow.sql.db:
    container_name: nimbleflow.sql.db
    image: postgres:${POSTGRES_TAG}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
      - "10500:5432"
    volumes:
      - nimbleflow.sql.db:/var/lib/postgresql/data
    restart: always

  nimbleflow.nosql.db:
    container_name: nimbleflow.nosql.db
    image: "amazon/dynamodb-local:latest"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    ports:
      - "10501:8000"
    volumes:
      - nimbleflow.nosql.db:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    restart: always

  nimbleflow.aspnetcore:
    build:
      context: ./AspDotNetCore
      dockerfile: Src/NimbleFlow.Api/Dockerfile

  nimbleflow.java:
    build: 
      context: ./SpringBoot
      dockerfile: Dockerfile.development

networks:
  default:
    name: nimbleflow-network

volumes:
  nimbleflow.sql.db:
    driver: local
  nimbleflow.nosql.db:
    driver: local