version: '3.9'

services:
  nimbleflow.sql.db:
    container_name: nimbleflow.sql.db
    image: postgres:${POSTGRES_TAG}
    environment:
      - POSTGRES_DB=${SQL_DATABASE_DATABASE}
      - POSTGRES_USER=${SQL_DATABASE_USER}
      - POSTGRES_PASSWORD=${SQL_DATABASE_PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${SQL_DATABASE_USER} -d ${SQL_DATABASE_DATABASE}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
      - "10500:${SQL_DATABASE_PORT}"
    volumes:
      - nimbleflow.sql.db:/var/lib/postgresql/data
      - .assets/initsql:/docker-entrypoint-initdb.d
    restart: always

  nimbleflow.nosql.db:
    container_name: nimbleflow.nosql.db
    image: "amazon/dynamodb-local:latest"
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    ports:
      - "10501:8000"
    volumes:
      - nimbleflow.nosql.db:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    restart: always

  nimbleflow.nosql.db.up:
    depends_on:
      - nimbleflow.nosql.db
    image: amazon/aws-cli
    container_name: nimbleflow.nosql.db.up
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    command:
      "dynamodb create-table
      --table-name order
      --attribute-definitions AttributeName=id,AttributeType=S
      --key-schema AttributeName=id,KeyType=HASH
      --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5
      --table-class STANDARD
      --endpoint-url ${NO_SQL_DATABASE_PATH}
      --region ${AWS_REGION}"

  nimbleflow.minio:
    image: minio/minio:latest
    container_name: nimbleflow.minio
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
    command: 'minio server /data/minio --console-address ":9090"'
    ports:
      - "10502:9000"
      - "10503:9090"
    volumes:
      - nimbleflow.minio:/data
    restart: always

  nimbleflow.minio.up:
    depends_on:
      - nimbleflow.minio
    image: amazon/aws-cli
    container_name: nimbleflow.minio.up
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_SERVICE_URL=${AWS_S3_SERVICE_URL}
      - AWS_REGION=${AWS_REGION}
    command:
      "s3api create-bucket
      --bucket nimbleflow
      --endpoint-url ${AWS_S3_SERVICE_URL}
      --acl public-read"

  nimbleflow.aspnetcore:
#    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_ECR_REPOSITORY}:${TAG}
    build:
      context: ./AspDotNetCore
      dockerfile: Src/NimbleFlow.Api/Dockerfile
    depends_on:
      nimbleflow.sql.db:
        condition: service_healthy
      nimbleflow.nosql.db:
        condition: service_started
      nimbleflow.minio:
        condition: service_started

  nimbleflow.java:
#    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_ECR_REPOSITORY}:${TAG}
    build:
      context: ./SpringBoot
      dockerfile: Dockerfile
    depends_on:
      nimbleflow.sql.db:
        condition: service_healthy
      nimbleflow.nosql.db:
        condition: service_started
      nimbleflow.minio:
        condition: service_started

networks:
  default:
    name: nimbleflow-network

volumes:
  nimbleflow.sql.db:
    driver: local
  nimbleflow.nosql.db:
    driver: local
  nimbleflow.minio:
    driver: local