package com.nimbleflow.api.domain.purchase;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.nimbleflow.api.config.DynamoDBConfig.ZonedDateTimeConverter;
import com.nimbleflow.api.domain.purchase.enums.PaymentMethod;
import lombok.*;

import java.time.ZonedDateTime;
import java.util.UUID;

@Data
@Builder
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "purchase")
public class Purchase {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private UUID id;

    @DynamoDBAttribute
    private UUID orderId;

    @DynamoDBAttribute
    private UUID tableId;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = ZonedDateTimeConverter.class)
    private ZonedDateTime purchaseDate;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    private PaymentMethod paymentMethod;

    @DynamoDBAttribute
    private boolean active;

}