package com.nimbleflow.api.domain.order;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.nimbleflow.api.config.DynamoDBConfig.ZonedDateTimeConverter;
import com.nimbleflow.api.domain.order.enums.PaymentMethod;
import com.nimbleflow.api.domain.product.ProductDTO;
import lombok.*;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.UUID;

@Data
@Builder
@ToString
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "order")
public class Order {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private UUID id;

    @DynamoDBAttribute
    private UUID tableId;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = ZonedDateTimeConverter.class)
    private ZonedDateTime orderDate;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    private PaymentMethod paymentMethod;

    @DynamoDBAttribute
    private List<ProductDTO> products;

    @DynamoDBAttribute
    private boolean active;

}