server:
  port: 8080
  error:
    include-stacktrace: always
    include-message: always
  servlet:
    context-path: /nimbleflow-api

amazon:
  aws:
    accesskey: xr5AHxbzBft1Fdqe0jC0
    secretkey: 1wP3wzMQrBcqx1vsf1DT
  dynamodb:
    endpoint: http://host.docker.internal:10501
    region: us-east-1