server:
  port: 8080
  error:
    include-stacktrace: always
    include-message: always
  servlet:
    context-path: /nimbleflow-api

amazon:
  aws:
    accesskey: ENC(L7U53JhIFJ+cFQGsWtWraIhD0WYtmiJxVvM24ZHUMoMelJSKtYHAHQAX1KAfhf9a2YRs064dHe3SBbyCAy+qeg==)
    secretkey: ENC(O+SV5znU+hattFn2mEGz6en8xPAWfsb8DmmfN9FRgjA6tPHafL+vrc4OiS6HpGggX38PooNFCS28yf8jTQncog==)
  dynamodb:
    endpoint: http://host.docker.internal:8000
    region: us-west-2

jasypt:
  encryptor: 
    password: ${NIMBLEFLOW_JASYPT_ENCRIPTION_KEY}


nimbleflow:
  username: ENC(56C5kO0xFt1Xei7Uwkmhh8ZDSiXxj61RPrXrKux5MCj/NHE1WufizNMgYaMCwI53LsZuqTr/vW/IoAifWmReGQ==)
  password: ENC(/96lnzwL6Zn1tz/zzWsCxk/YTIBm9njzAr5DrrTWDyPi6l8aF5frcyWJsnNXwj5cjTOWUhxbzP4e9U70YlaCzg==)
  jwt:
    signing-key: ENC(FWqF9i80y6nLLTD76GjeEQez/stmOk+tMUKdCpelVG5U6JziYDRtQa5vtJeVKNKCQavZAY88lKmCTwUo1sz/cgAbym+m+BdHwpineTaWWvxAhL/0e5loWvbCXrm4xeg1D56bKQ46xrCORmRg91PhAZZvvqnehOOGjoUksj6HQfxyYDPpMNPEXxv0A9qfrLhBjMLbAl2SIsJwtnAdZ9EM1cHwYjY44mym6AVn8RdChxU=)