server:
  port: 8080
  error:
    include-stacktrace: always
    include-message: always
  servlet:
    context-path: /nimbleflow-api

amazon:
  aws:
    accesskey: ENC(msWkKSV1HmIHpBPlv1dbxF7TSqAf6y9rN7fZ8bGjw6A/3fbjGjVxkFLV91aGK7fOB0bglf5s8dA52y1cHd9ynQ==)
    secretkey: ENC(gwUhlcZTOMCuj2VWZvdtHrxMmFI/OQtbpKXnBV3jJFXbURE89Rx1uzeG+MsDwy+jK1ff38Ging4gsfIfvUkPK4XW56gcTvJg3wvmxS+Jw4I=)
  dynamodb:
    endpoint: ${NO_SQL_DATABASE_PATH}
    region: ${AWS_REGION}

jasypt:
  encryptor: 
    password: ${NIMBLEFLOW_JASYPT_ENCRIPTION_KEY}


nimbleflow:
  username: ENC(6fzepUNAo6qH1UY9/B01MLD1OQ6w9u2tyk1+h9rY15RmgR/RV1TqvDpbLyXSGtIKXOJsfS5mLBiPJKKbto1Bbw==)
  password: ENC(XSKA7L4aSLGFaKRTFxCLa0A1ksPKLhtROLGmGJdsUIy8wNwQrkLjc5e7r/9PNwVqaRacn5Q1wV+SdLZ3xgSjQg==)
  integration-token: ${NIMBLEFLOW_JAVA_API_INTEGRATION_TOKEN}
  jwt:
    signing-key: ENC(k6344MkXQgxJQumRjWzUwJJvD0RSGIZUD39eAPeLtIxmMp5WKXLq7ndiYzBes/1HOEB3+6OjJYwV/NGLp1t16Kdh32rmzyh25RWfvVuWz5by9E09XS4TEVYUwB7sG/w4)